# Generated by Django 3.2.8 on 2021-10-18 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('long_meaning_by_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('long_meaning_by_hours', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('s_time', models.DateTimeField()),
                ('e_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('now', 'meating is now'), ('end', 'meating end'), ('soon', 'meating in future')], default=('soon', 'meating in future'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meating_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('1', (('1', 'building 1'), ('2', 'building 2')))], default='', max_length=50)),
                ('floor', models.CharField(default='', max_length=1)),
                ('room', models.CharField(default='', max_length=1)),
            ],
        ),
    ]
