# Generated by Django 3.2.8 on 2021-10-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meating_calendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meating_rooms',
        ),
        migrations.AddField(
            model_name='meating',
            name='room',
            field=models.CharField(choices=[('1', (('1', 'building 1'), ('2', 'building 2')))], default='', max_length=50),
        ),
    ]
