# Generated by Django 3.2.8 on 2021-10-18 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meating_calendar', '0002_auto_20211018_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='_id',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='meating',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meating_calendar.accounts'),
        ),
    ]
