# Generated by Django 3.2.8 on 2021-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meating_calendar', '0005_alter_accounts__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meating',
            name='room',
            field=models.CharField(choices=[('Building 1', (('Floor 1', 'Room 1'),))], default='', max_length=50),
        ),
    ]
