# Generated by Django 3.2.8 on 2021-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meating_calendar', '0007_auto_20211019_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meating',
            name='room',
            field=models.CharField(default='', max_length=50),
        ),
    ]
