# Generated by Django 3.2.8 on 2021-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meating_calendar', '0008_alter_meating_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meating',
            name='room',
            field=models.CharField(choices=[('', 'B1-F1-R1'), ('', 'B2-F3-R1')], default='', max_length=50),
        ),
    ]
