# Generated by Django 3.2.8 on 2021-10-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meating_calendar', '0010_auto_20211019_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meating',
            old_name='building_choices',
            new_name='room',
        ),
    ]
