# Generated by Django 3.2.8 on 2021-10-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meating_calendar', '0011_rename_building_choices_meating_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meating',
            name='status',
            field=models.CharField(choices=[('now', 'meating is active'), ('end', 'meating end'), ('soon', 'meating in future')], default=('soon', 'meating in future'), max_length=50),
        ),
    ]
